export interface LanguageConfig {
  code: string
  name: string
  nativeName: string
  locale: string
  region: 'india' | 'international'
  isRTL?: boolean
  translations: {
    YES: string
    NO: string
    HELP: string
    WATER: string
    HI: string
    'I NEED WATER': string
    'TURN ON LIGHTS': string
  }
}

export const SUPPORTED_LANGUAGES: LanguageConfig[] = [
  // ─── 16 INDIAN LANGUAGES ──────────────────────────────────────────────────
  {
    code: 'as',
    name: 'Assamese',
    nativeName: 'অসমীয়া',
    locale: 'as-IN',
    region: 'india',
    translations: {
      YES: 'হয়',
      NO: 'নহয়',
      HELP: 'সহায়',
      WATER: 'পানী',
      HI: 'নমস্কাৰ',
      'I NEED WATER': 'মোক পানী লাগে',
      'TURN ON LIGHTS': 'পোহৰ জ্বলাই দিয়ক',
    },
  },
  {
    code: 'bn',
    name: 'Bengali',
    nativeName: 'বাংলা',
    locale: 'bn-IN',
    region: 'india',
    translations: {
      YES: 'হ্যাঁ',
      NO: 'না',
      HELP: 'সাহায্য',
      WATER: 'জল',
      HI: 'নমস্কার',
      'I NEED WATER': 'আমার জল চাই',
      'TURN ON LIGHTS': 'আলো জ্বালান',
    },
  },
  {
    code: 'gu',
    name: 'Gujarati',
    nativeName: 'ગુજરાતી',
    locale: 'gu-IN',
    region: 'india',
    translations: {
      YES: 'હા',
      NO: 'ના',
      HELP: 'મદદ',
      WATER: 'પાણી',
      HI: 'નમસ્તે',
      'I NEED WATER': 'મને પાણી જોઈએ છે',
      'TURN ON LIGHTS': 'લાઇટ ચાલુ કરો',
    },
  },
  {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    locale: 'hi-IN',
    region: 'india',
    translations: {
      YES: 'हाँ',
      NO: 'नहीं',
      HELP: 'मदद',
      WATER: 'पानी',
      HI: 'नमस्ते',
      'I NEED WATER': 'मुझे पानी चाहिए',
      'TURN ON LIGHTS': 'लाइट जलाएं',
    },
  },
  {
    code: 'kn',
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    locale: 'kn-IN',
    region: 'india',
    translations: {
      YES: 'ಹೌದು',
      NO: 'ಇಲ್ಲ',
      HELP: 'ಸಹಾಯ',
      WATER: 'ನೀರು',
      HI: 'ನಮಸ್ಕಾರ',
      'I NEED WATER': 'ನನಗೆ ನೀರು ಬೇಕು',
      'TURN ON LIGHTS': 'ಲೈಟ್ ಹಾಕಿ',
    },
  },
  {
    code: 'ks',
    name: 'Kashmiri',
    nativeName: 'कश्मीरी',
    locale: 'ks-IN',
    region: 'india',
    translations: {
      YES: 'आ',
      NO: 'न',
      HELP: 'मदद',
      WATER: 'आब',
      HI: 'आदाब',
      'I NEED WATER': 'में छि आब गछान',
      'TURN ON LIGHTS': 'लाइट चालु करिव',
    },
  },
  {
    code: 'mai',
    name: 'Maithili',
    nativeName: 'मैथिली',
    locale: 'mai-IN',
    region: 'india',
    translations: {
      YES: 'हाँ',
      NO: 'नहि',
      HELP: 'मदद',
      WATER: 'पानी',
      HI: 'प्रणाम',
      'I NEED WATER': 'हमरा पानी चाही',
      'TURN ON LIGHTS': 'लाइट बजारू',
    },
  },
  {
    code: 'ml',
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    locale: 'ml-IN',
    region: 'india',
    translations: {
      YES: 'അതെ',
      NO: 'ഇല്ല',
      HELP: 'സഹായം',
      WATER: 'വെള്ളം',
      HI: 'നമസ്കാരം',
      'I NEED WATER': 'എനിക്ക് വെള്ളം വേണം',
      'TURN ON LIGHTS': 'ലൈറ്റ് ഇടുക',
    },
  },
  {
    code: 'mni',
    name: 'Manipuri',
    nativeName: 'মৈতৈলোন্',
    locale: 'mni-IN',
    region: 'india',
    translations: {
      YES: 'હોય',
      NO: 'નત્તે',
      HELP: 'મતેꯡ',
      WATER: 'ઈશિંગ',
      HI: 'ખુરુમજરી',
      'I NEED WATER': 'ઐ ઈશિંગ પામ્મી',
      'TURN ON LIGHTS': 'થાનજબી થાન્બિયુ',
    },
  },
  {
    code: 'mr',
    name: 'Marathi',
    nativeName: 'मराठी',
    locale: 'mr-IN',
    region: 'india',
    translations: {
      YES: 'होय',
      NO: 'नाही',
      HELP: 'मदत',
      WATER: 'पाणी',
      HI: 'नमस्कार',
      'I NEED WATER': 'मला पाणी हवे आहे',
      'TURN ON LIGHTS': 'लाइट लावा',
    },
  },
  {
    code: 'ne',
    name: 'Nepali',
    nativeName: 'नेपाली',
    locale: 'ne-NP',
    region: 'india',
    translations: {
      YES: 'हो',
      NO: 'होइन',
      HELP: 'मद्दत',
      WATER: 'पानी',
      HI: 'नमस्ते',
      'I NEED WATER': 'मलाई पानी चाहिन्छ',
      'TURN ON LIGHTS': 'बत्ती बाल्नुहोस्',
    },
  },
  {
    code: 'or',
    name: 'Odia',
    nativeName: 'ଓଡ଼ିଆ',
    locale: 'or-IN',
    region: 'india',
    translations: {
      YES: 'ହଁ',
      NO: 'ନାହିଁ',
      HELP: 'ସାହାଯ୍ୟ',
      WATER: 'ପାଣି',
      HI: 'ନମସ୍କାର',
      'I NEED WATER': 'ମୋତେ ପାଣି ଦରକାର',
      'TURN ON LIGHTS': 'ଲାଇଟ୍ ଅନ୍ କରନ୍ତୁ',
    },
  },
  {
    code: 'pa',
    name: 'Punjabi',
    nativeName: 'ਪੰਜਾਬੀ',
    locale: 'pa-IN',
    region: 'india',
    translations: {
      YES: 'ਹਾਂ',
      NO: 'ਨਹੀਂ',
      HELP: 'ਮਦਦ',
      WATER: 'ਪਾਣੀ',
      HI: 'ਸਤਿ ਸ਼੍ਰੀ ਅਕਾਲ',
      'I NEED WATER': 'ਮੈਨੂੰ ਪਾਣੀ ਚਾਹੀਦਾ ਹੈ',
      'TURN ON LIGHTS': 'ਲਾਇਟ ਚਲਾਓ',
    },
  },
  {
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    locale: 'ta-IN',
    region: 'india',
    translations: {
      YES: 'ஆம்',
      NO: 'இல்லை',
      HELP: 'உதவி',
      WATER: 'தண்ணீர்',
      HI: 'வணக்கம்',
      'I NEED WATER': 'எனக்கு தண்ணீர் வேண்டும்',
      'TURN ON LIGHTS': 'விளக்கை போடுங்கள்',
    },
  },
  {
    code: 'te',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    locale: 'te-IN',
    region: 'india',
    translations: {
      YES: 'అవును',
      NO: 'కాదు',
      HELP: 'సహాయం',
      WATER: 'నీరు',
      HI: 'నమస్కారం',
      'I NEED WATER': 'నాకు మంచి నీళ్ళు కావాలి',
      'TURN ON LIGHTS': 'లైట్ వేయండి',
    },
  },
  {
    code: 'ur',
    name: 'Urdu',
    nativeName: 'اردو',
    locale: 'ur-PK',
    region: 'india',
    isRTL: true,
    translations: {
      YES: 'جی ہاں',
      NO: 'نہیں۔',
      HELP: 'مدد',
      WATER: 'پانی',
      HI: 'السلام علیکم',
      'I NEED WATER': 'مجھے پانی چاہیے',
      'TURN ON LIGHTS': 'لائٹ آن کریں',
    },
  },

  // ─── 8 INTERNATIONAL LANGUAGES ─────────────────────────────────────────────
  {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    locale: 'en-US',
    region: 'international',
    translations: {
      YES: 'YES',
      NO: 'NO',
      HELP: 'HELP',
      WATER: 'WATER',
      HI: 'HI',
      'I NEED WATER': 'I NEED WATER',
      'TURN ON LIGHTS': 'TURN ON LIGHTS',
    },
  },
  {
    code: 'es',
    name: 'Spanish',
    nativeName: 'Español',
    locale: 'es-ES',
    region: 'international',
    translations: {
      YES: 'SÍ',
      NO: 'NO',
      HELP: 'AYUDA',
      WATER: 'AGUA',
      HI: 'HOLA',
      'I NEED WATER': 'NECESITO AGUA',
      'TURN ON LIGHTS': 'ENCIENDE LAS LUCES',
    },
  },
  {
    code: 'fr',
    name: 'French',
    nativeName: 'Français',
    locale: 'fr-FR',
    region: 'international',
    translations: {
      YES: 'OUI',
      NO: 'NON',
      HELP: 'AIDE',
      WATER: 'EAU',
      HI: 'BONJOUR',
      'I NEED WATER': "J'AI BESOIN D'EAU",
      'TURN ON LIGHTS': 'ALLUMEZ LES LUMIÈRES',
    },
  },
  {
    code: 'de',
    name: 'German',
    nativeName: 'Deutsch',
    locale: 'de-DE',
    region: 'international',
    translations: {
      YES: 'JA',
      NO: 'NEIN',
      HELP: 'HILFE',
      WATER: 'WASSER',
      HI: 'HALLO',
      'I NEED WATER': 'ICH BRAUCHE WASSER',
      'TURN ON LIGHTS': 'LICHT EINSCHALTEN',
    },
  },
  {
    code: 'ar',
    name: 'Arabic',
    nativeName: 'العربية',
    locale: 'ar-SA',
    region: 'international',
    isRTL: true,
    translations: {
      YES: 'نعم',
      NO: 'لا',
      HELP: 'مساعدة',
      WATER: 'ماء',
      HI: 'مرحبا',
      'I NEED WATER': 'أحتاج إلى الماء',
      'TURN ON LIGHTS': 'قم بتشغيل الأضواء',
    },
  },
  {
    code: 'zh',
    name: 'Chinese',
    nativeName: '中文',
    locale: 'zh-CN',
    region: 'international',
    translations: {
      YES: '是的',
      NO: '不',
      HELP: '帮助',
      WATER: '水',
      HI: '你好',
      'I NEED WATER': '我需要水',
      'TURN ON LIGHTS': '开灯',
    },
  },
  {
    code: 'ja',
    name: 'Japanese',
    nativeName: '日本語',
    locale: 'ja-JP',
    region: 'international',
    translations: {
      YES: 'はい',
      NO: 'いいえ',
      HELP: '助けて',
      WATER: '水',
      HI: 'こんにちは',
      'I NEED WATER': '水をお願いします',
      'TURN ON LIGHTS': '電気をつけてください',
    },
  },
  {
    code: 'ko',
    name: 'Korean',
    nativeName: '한국어',
    locale: 'ko-KR',
    region: 'international',
    translations: {
      YES: '네',
      NO: '아니오',
      HELP: '도와주세요',
      WATER: '물',
      HI: '안녕하세요',
      'I NEED WATER': '물이 필요합니다',
      'TURN ON LIGHTS': '불을 켜주세요',
    },
  },
]

export const TOTAL_LANGUAGES_COUNT = SUPPORTED_LANGUAGES.length
export const INDIAN_LANGUAGES_COUNT = SUPPORTED_LANGUAGES.filter((l) => l.region === 'india').length
export const INTERNATIONAL_LANGUAGES_COUNT = SUPPORTED_LANGUAGES.filter((l) => l.region === 'international').length
