import { motion } from 'framer-motion'
import { Cpu, Activity, Disc, GitCommit, BatteryCharging, ArrowRight } from 'lucide-react'

const HARDWARE_COMPONENTS = [
  {
    id: 'esp32-s3',
    name: 'ESP32-S3',
    category: 'Main Microcontroller',
    icon: Cpu,
    role: 'Handles sensor data acquisition, processing, and communication with the rest of the system.',
    description:
      '32-bit Xtensa dual-core LX7 processor at 240 MHz with vector instructions for on-device TinyML neural inference and integrated Wi-Fi / BLE radio.',
    specs: ['240 MHz Dual-Core', '512 KB SRAM + 8MB PSRAM', '< 45 mW Peak Power'],
    svgGraphic: (
      <svg viewBox="0 0 200 140" className="w-full h-36" aria-label="ESP32-S3 Chip Diagram">
        <rect x="30" y="20" width="140" height="100" rx="8" fill="#18181b" stroke="#3f3f46" strokeWidth="2" />
        <rect x="50" y="35" width="100" height="70" rx="4" fill="#27272a" />
        <rect x="70" y="50" width="60" height="40" rx="2" fill="#09090b" stroke="#10b981" strokeWidth="1.5" />
        <circle cx="100" cy="70" r="4" fill="#10b981" className="animate-pulse" />
        {/* Pins */}
        {Array.from({ length: 8 }).map((_, i) => (
          <g key={i}>
            <rect x={38 + i * 16} y="10" width="8" height="10" rx="1" fill="#d4d4d8" />
            <rect x={38 + i * 16} y="120" width="8" height="10" rx="1" fill="#d4d4d8" />
          </g>
        ))}
        <text x="100" y="102" textAnchor="middle" fill="#a1a1aa" fontSize="9" fontFamily="monospace" fontWeight="bold">
          ESP32-S3 WROOM
        </text>
      </svg>
    ),
  },
  {
    id: 'emg-sensor',
    name: 'Muscle / EMG Sensor',
    category: 'Muscle-Signal Acquisition',
    icon: Activity,
    role: 'Captures electrical activity generated by muscle movement and provides the signal used by BoneTalk.',
    description:
      'Analog front-end (AFE) circuit with high common-mode rejection ratio (CMRR) and bandpass filtering for microvolt-level biopotentials.',
    specs: ['20 - 450 Hz Bandpass', '1000x Amplification', '-110 dB CMRR'],
    svgGraphic: (
      <svg viewBox="0 0 200 140" className="w-full h-36" aria-label="EMG Sensor Module Diagram">
        <rect x="25" y="20" width="150" height="100" rx="8" fill="#064e3b" stroke="#047857" strokeWidth="2" />
        <rect x="40" y="35" width="45" height="40" rx="4" fill="#022c22" stroke="#10b981" strokeWidth="1" />
        <rect x="100" y="35" width="60" height="70" rx="4" fill="#022c22" />
        {/* Waveform graphic on board */}
        <path d="M45 55 L55 45 L65 65 L75 55" fill="none" stroke="#34d399" strokeWidth="2" />
        {/* Terminal block */}
        <rect x="40" y="85" width="45" height="20" rx="2" fill="#15803d" />
        <circle cx="50" cy="95" r="3" fill="#fef08a" />
        <circle cx="62.5" cy="95" r="3" fill="#fef08a" />
        <circle cx="75" cy="95" r="3" fill="#fef08a" />
        <text x="100" y="112" textAnchor="middle" fill="#a7f3d0" fontSize="9" fontFamily="monospace">
          EMG AFE BOARD
        </text>
      </svg>
    ),
  },
  {
    id: 'electrodes',
    name: 'Electrodes',
    category: 'Signal Detection',
    icon: Disc,
    role: 'Used to detect muscle activity and transfer the signal to the sensing circuit.',
    description:
      'Clinical-grade Ag/AgCl surface contact electrodes positioned at key neck extensor and flexor muscle sites for low-impedance biopotential pickup.',
    specs: ['Ag/AgCl Conductive Contacts', 'Low Contact Impedance', 'Flexible Snap Leads'],
    svgGraphic: (
      <svg viewBox="0 0 200 140" className="w-full h-36" aria-label="Biopotential Electrodes Diagram">
        <circle cx="60" cy="70" r="38" fill="#f4f4f5" stroke="#d4d4d8" strokeWidth="2" />
        <circle cx="60" cy="70" r="22" fill="#e4e4e7" />
        <circle cx="60" cy="70" r="10" fill="#ca8a04" />
        <circle cx="140" cy="70" r="38" fill="#f4f4f5" stroke="#d4d4d8" strokeWidth="2" />
        <circle cx="140" cy="70" r="22" fill="#e4e4e7" />
        <circle cx="140" cy="70" r="10" fill="#ca8a04" />
        <path d="M70 70 Q 100 40 130 70" fill="none" stroke="#10b981" strokeWidth="2" strokeDasharray="3 3" />
        <text x="100" y="122" textAnchor="middle" fill="#71717a" fontSize="9" fontFamily="monospace">
          AG/AGCL SURFACE CONTACTS
        </text>
      </svg>
    ),
  },
  {
    id: 'jumper-wires',
    name: 'Jumper Wires / Connections',
    category: 'Hardware Connectivity',
    icon: GitCommit,
    role: 'Connect the sensors and electronic components together during prototyping.',
    description:
      'High-flexibility multi-strand ribbon connectors and shielded signal cabling designed to minimize movement artifacts and crosstalk.',
    specs: ['Shielded Cabling', 'Low-Resistance Contacts', 'Strain Relief Sleeves'],
    svgGraphic: (
      <svg viewBox="0 0 200 140" className="w-full h-36" aria-label="Jumper Wires Harness Diagram">
        <path d="M30 40 C 80 10, 120 70, 170 40" fill="none" stroke="#ef4444" strokeWidth="3" />
        <path d="M30 70 C 80 40, 120 100, 170 70" fill="none" stroke="#10b981" strokeWidth="3" />
        <path d="M30 100 C 80 70, 120 130, 170 100" fill="none" stroke="#3b82f6" strokeWidth="3" />
        <rect x="20" y="30" width="15" height="80" rx="3" fill="#27272a" />
        <rect x="165" y="30" width="15" height="80" rx="3" fill="#27272a" />
        <text x="100" y="125" textAnchor="middle" fill="#71717a" fontSize="9" fontFamily="monospace">
          SIGNAL HARNESS
        </text>
      </svg>
    ),
  },
  {
    id: 'power-battery',
    name: 'Power Supply / Battery',
    category: 'Portable Power',
    icon: BatteryCharging,
    role: 'Provides power to the BoneTalk hardware system.',
    description:
      'Rechargeable Lithium-Polymer (LiPo) battery unit with integrated power management IC (PMIC) providing stable 3.3V power rails for wearable operation.',
    specs: ['3.7V 500mAh LiPo', 'Integrated PMIC Protection', 'USB-C Rechargeable'],
    svgGraphic: (
      <svg viewBox="0 0 200 140" className="w-full h-36" aria-label="Battery Pack Diagram">
        <rect x="40" y="30" width="110" height="80" rx="6" fill="# silver" stroke="#9ca3af" strokeWidth="2" className="fill-zinc-200" />
        <rect x="150" y="55" width="10" height="30" rx="2" fill="#6b7280" />
        <rect x="55" y="45" width="80" height="50" rx="3" fill="#059669" />
        <path d="M90 55 L80 72 L95 72 L85 85" fill="none" stroke="#ffffff" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
        <text x="95" y="124" textAnchor="middle" fill="#71717a" fontSize="9" fontFamily="monospace">
          LIPO POWER CELL
        </text>
      </svg>
    ),
  },
]

const SIGNAL_FLOW_STEPS = [
  'Muscle Activity',
  'EMG Sensor',
  'ESP32-S3',
  'Signal Processing',
  'AI Model',
  'Communication',
]

export function HardwareShowcaseSection() {
  return (
    <section id="hardware-showcase" className="bg-white py-24 md:py-32 border-t border-zinc-200">
      <div className="mx-auto max-w-7xl px-6 md:px-10">
        {/* Header */}
        <div className="max-w-3xl mb-16">
          <span className="text-sm font-semibold tracking-wider text-emerald-700 uppercase">
            Prototype Architecture
          </span>
          <h2 className="mt-3 font-display text-3xl sm:text-4xl lg:text-5xl font-extrabold tracking-tight text-zinc-900 leading-tight">
            The Technology Behind BoneTalk
          </h2>
          <blockquote className="mt-4 text-lg text-zinc-600 leading-relaxed font-normal border-l-4 border-emerald-600 pl-4 py-1 italic bg-emerald-50/50 rounded-r-lg">
            BoneTalk combines embedded hardware, muscle-signal sensing, and intelligent processing to transform intentional muscle activity into communication.
          </blockquote>
        </div>

        {/* Hardware Component Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mb-20">
          {HARDWARE_COMPONENTS.map((item, index) => {
            const Icon = item.icon
            return (
              <motion.div
                key={item.id}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: index * 0.08 }}
                className="flex flex-col justify-between rounded-2xl bg-zinc-50 border border-zinc-200/90 p-6 shadow-sm hover:shadow-md hover:border-emerald-300 transition-all group"
              >
                <div>
                  {/* Visual Graphic Box */}
                  <div className="rounded-xl bg-white p-3 border border-zinc-200 mb-6 flex items-center justify-center overflow-hidden">
                    {item.svgGraphic}
                  </div>

                  {/* Component Title & Subtitle */}
                  <div className="flex items-start justify-between gap-3 mb-2">
                    <div>
                      <h3 className="text-xl font-bold text-zinc-900 group-hover:text-emerald-700 transition-colors">
                        {item.name}
                      </h3>
                      <span className="text-xs font-semibold text-emerald-800 tracking-wide uppercase font-mono block mt-0.5">
                        {item.category}
                      </span>
                    </div>
                    <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-emerald-100 text-emerald-700 flex-shrink-0">
                      <Icon size={18} />
                    </div>
                  </div>

                  {/* Role in BoneTalk */}
                  <div className="mt-4 mb-4 p-3 rounded-lg bg-white border border-zinc-200/80">
                    <span className="text-xs font-bold text-zinc-900 block mb-1">Role in BoneTalk:</span>
                    <p className="text-xs text-zinc-700 leading-relaxed font-medium">
                      {item.role}
                    </p>
                  </div>

                  {/* Technical Description */}
                  <p className="text-xs text-zinc-600 leading-relaxed mb-4">
                    {item.description}
                  </p>
                </div>

                {/* Specs Tags */}
                <div className="pt-4 border-t border-zinc-200/80 flex flex-wrap gap-1.5">
                  {item.specs.map((spec) => (
                    <span key={spec} className="text-[11px] font-mono text-zinc-600 bg-white border border-zinc-200 px-2 py-0.5 rounded-md">
                      {spec}
                    </span>
                  ))}
                </div>
              </motion.div>
            )
          })}
        </div>

        {/* Compact Signal Flow Visual */}
        <div className="rounded-3xl bg-zinc-900 p-8 md:p-12 text-white shadow-xl">
          <div className="text-center max-w-xl mx-auto mb-8">
            <span className="text-xs font-mono text-emerald-400 font-bold tracking-widest uppercase block mb-1">
              End-to-End System Pipeline
            </span>
            <h3 className="text-2xl font-bold text-white">How the Hardware Components Work Together</h3>
          </div>

          <div className="flex flex-wrap items-center justify-center gap-2 md:gap-3">
            {SIGNAL_FLOW_STEPS.map((step, idx) => (
              <div key={step} className="flex items-center gap-2 md:gap-3">
                <div className="rounded-xl bg-zinc-800 border border-zinc-700 px-4 py-3 text-center">
                  <span className="block text-[10px] font-mono text-emerald-400 font-bold mb-0.5">
                    STEP 0{idx + 1}
                  </span>
                  <span className="text-xs md:text-sm font-bold text-zinc-100 whitespace-nowrap">
                    {step}
                  </span>
                </div>
                {idx < SIGNAL_FLOW_STEPS.length - 1 && (
                  <ArrowRight size={16} className="text-emerald-500 flex-shrink-0" />
                )}
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  )
}
