import { motion } from 'framer-motion'
import { Activity, Cpu, Volume2, CheckCircle } from 'lucide-react'

const STEPS = [
  {
    number: '01',
    icon: Activity,
    title: 'Sense Muscle Activity',
    description:
      'Clinical-grade surface EMG electrodes capture microvolt-level biopotential signals generated by intentional neck muscle movements.',
    badge: '1000 Hz Sampling',
  },
  {
    number: '02',
    icon: Cpu,
    title: 'Process with On-Device AI',
    description:
      'The ESP32-S3 microcontroller runs a lightweight TinyML neural network locally to filter noise and classify contraction patterns in real time.',
    badge: '< 12ms Processing',
  },
  {
    number: '03',
    icon: Volume2,
    title: 'Synthesize Instant Speech',
    description:
      'Recognized intent is mapped directly into audible voice output or text commands, giving non-verbal users an immediate way to express themselves.',
    badge: 'Real-time Voice',
  },
]

export function HowItWorksSection() {
  return (
    <section id="how-it-works" className="bg-zinc-50 py-24 md:py-32 border-y border-zinc-200/80">
      <div className="mx-auto max-w-7xl px-6 md:px-10">
        <div className="max-w-3xl mb-16">
          <span className="text-sm font-semibold tracking-wider text-emerald-700 uppercase">
            Simple 3-Step Architecture
          </span>
          <h2 className="mt-3 font-display text-3xl sm:text-4xl lg:text-5xl font-extrabold tracking-tight text-zinc-900 leading-tight">
            How BoneTalk restores your natural voice.
          </h2>
          <p className="mt-4 text-lg text-zinc-600 leading-relaxed font-normal">
            BoneTalk bypasses damaged vocal pathways by capturing signal intent directly at the muscle group.
          </p>
        </div>

        <div className="grid grid-cols-1 gap-8 md:grid-cols-3">
          {STEPS.map((step, index) => {
            const Icon = step.icon
            return (
              <motion.div
                key={step.number}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                className="relative flex flex-col justify-between rounded-2xl bg-white p-8 border border-zinc-200 shadow-sm hover:shadow-md transition-shadow"
              >
                <div>
                  <div className="flex items-center justify-between mb-6">
                    <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700">
                      <Icon size={24} />
                    </div>
                    <span className="font-mono text-2xl font-bold text-zinc-300">
                      {step.number}
                    </span>
                  </div>

                  <h3 className="text-xl font-bold text-zinc-900 mb-3">
                    {step.title}
                  </h3>

                  <p className="text-base text-zinc-600 leading-relaxed font-normal">
                    {step.description}
                  </p>
                </div>

                <div className="mt-8 pt-4 border-t border-zinc-100 flex items-center gap-2 text-xs font-semibold text-emerald-800">
                  <CheckCircle size={14} className="text-emerald-600" />
                  <span>{step.badge}</span>
                </div>
              </motion.div>
            )
          })}
        </div>
      </div>
    </section>
  )
}
